
// models/cashFlow.js
export default function CashFlowModel(sequelize, DataTypes) {
  return sequelize.define(
    'cash_flow_cash_flow',
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      symbol: { type: DataTypes.TEXT, allowNull: true, primaryKey: true },
      col_unknown: { type: DataTypes.TEXT, allowNull: true },
      Mar_2025: { type: DataTypes.TEXT, allowNull: true },
      Mar_2019: { type: DataTypes.TEXT, allowNull: true },
      Mar_2021: { type: DataTypes.TEXT, allowNull: true },
      Mar_2017: { type: DataTypes.TEXT, allowNull: true },
      Mar_2018: { type: DataTypes.TEXT, allowNull: true },
      Mar_2015: { type: DataTypes.TEXT, allowNull: true },
      Mar_2023: { type: DataTypes.TEXT, allowNull: true },
      Mar_2020: { type: DataTypes.TEXT, allowNull: true },
      Mar_2016: { type: DataTypes.TEXT, allowNull: true },
      Mar_2022: { type: DataTypes.TEXT, allowNull: true },
      Mar_2024: { type: DataTypes.TEXT, allowNull: true },
      Mar_2014: { type: DataTypes.TEXT, allowNull: true },
      Mar_2011: { type: DataTypes.TEXT, allowNull: true },
      Dec_2011: { type: DataTypes.TEXT, allowNull: true },
      Dec_2012: { type: DataTypes.TEXT, allowNull: true },
      Dec_2021: { type: DataTypes.TEXT, allowNull: true },
      Dec_2020: { type: DataTypes.TEXT, allowNull: true },
      Dec_2019: { type: DataTypes.TEXT, allowNull: true },
      Dec_2016: { type: DataTypes.TEXT, allowNull: true },
      Dec_2014: { type: DataTypes.TEXT, allowNull: true },
      Dec_2017: { type: DataTypes.TEXT, allowNull: true },
      Dec_2018: { type: DataTypes.TEXT, allowNull: true },
      Dec_2013: { type: DataTypes.TEXT, allowNull: true },
      Dec_2015: { type: DataTypes.TEXT, allowNull: true },
      Jun_2016: { type: DataTypes.TEXT, allowNull: true },
      Jun_2018: { type: DataTypes.TEXT, allowNull: true },
      Jun_2019: { type: DataTypes.TEXT, allowNull: true },
      Jun_2022: { type: DataTypes.TEXT, allowNull: true },
      Jun_2024: { type: DataTypes.TEXT, allowNull: true },
      Jun_2025: { type: DataTypes.TEXT, allowNull: true },
      Jun_2015: { type: DataTypes.TEXT, allowNull: true },
      Jun_2017: { type: DataTypes.TEXT, allowNull: true },
      Jun_2021: { type: DataTypes.TEXT, allowNull: true },
      Jun_2023: { type: DataTypes.TEXT, allowNull: true },
      Jun_2014: { type: DataTypes.TEXT, allowNull: true },
      Jun_2020: { type: DataTypes.TEXT, allowNull: true },
      Mar_2013: { type: DataTypes.TEXT, allowNull: true },
      Mar_2006: { type: DataTypes.TEXT, allowNull: true },
      Mar_2009: { type: DataTypes.TEXT, allowNull: true },
      Mar_2010: { type: DataTypes.TEXT, allowNull: true },
      Mar_2007: { type: DataTypes.TEXT, allowNull: true },
      Mar_2008: { type: DataTypes.TEXT, allowNull: true },
      Mar_2012: { type: DataTypes.TEXT, allowNull: true },
      Sep_2013: { type: DataTypes.TEXT, allowNull: true },
    },
    { tableName: 'cash_flow_cash_flow', timestamps: false, freezeTableName: true }
  );
}
