// models/shareholdingPattern.js
export default function ShareholdingPatternModel(sequelize, DataTypes) {
  return sequelize.define(
    'shareholding_pattern_shareholding_pattern',
    {
      id: {
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
      },
      symbol: { type: DataTypes.TEXT, allowNull: true },
      col_unknown: { type: DataTypes.TEXT, allowNull: true },
      Mar_2025: { type: DataTypes.TEXT, allowNull: true },
      Mar_2019: { type: DataTypes.TEXT, allowNull: true },
      Mar_2021: { type: DataTypes.TEXT, allowNull: true },
      Mar_2018: { type: DataTypes.TEXT, allowNull: true },
      Mar_2017: { type: DataTypes.TEXT, allowNull: true },
      Mar_2023: { type: DataTypes.TEXT, allowNull: true },
      Jun_2025: { type: DataTypes.TEXT, allowNull: true },
      Mar_2020: { type: DataTypes.TEXT, allowNull: true },
      Mar_2022: { type: DataTypes.TEXT, allowNull: true },
      Mar_2024: { type: DataTypes.TEXT, allowNull: true },
      Aug_2025: { type: DataTypes.TEXT, allowNull: true },
      Aug_2019: { type: DataTypes.TEXT, allowNull: true },
      Dec_2015: { type: DataTypes.TEXT, allowNull: true },
      Jan_2016: { type: DataTypes.TEXT, allowNull: true },
      Feb_2016: { type: DataTypes.TEXT, allowNull: true },
      Jul_2025: { type: DataTypes.TEXT, allowNull: true },
      Jun_2024: { type: DataTypes.TEXT, allowNull: true },
      Mar_2015: { type: DataTypes.TEXT, allowNull: true },
      Mar_2016: { type: DataTypes.TEXT, allowNull: true },
      Sep_2025: { type: DataTypes.TEXT, allowNull: true },
      Dec_2023: { type: DataTypes.TEXT, allowNull: true },
      Jun_2022: { type: DataTypes.TEXT, allowNull: true },
      Dec_2019: { type: DataTypes.TEXT, allowNull: true },
      Jun_2018: { type: DataTypes.TEXT, allowNull: true },
      Jun_2019: { type: DataTypes.TEXT, allowNull: true },
      Jun_2020: { type: DataTypes.TEXT, allowNull: true },
      Dec_2016: { type: DataTypes.TEXT, allowNull: true },
      Dec_2022: { type: DataTypes.TEXT, allowNull: true },
      Sep_2020: { type: DataTypes.TEXT, allowNull: true },
      Sep_2019: { type: DataTypes.TEXT, allowNull: true },
      Apr_2001: { type: DataTypes.TEXT, allowNull: true },
      Mar_2008: { type: DataTypes.TEXT, allowNull: true },
      Sep_2024: { type: DataTypes.TEXT, allowNull: true },
      Dec_2012: { type: DataTypes.TEXT, allowNull: true },
      Jan_2018: { type: DataTypes.TEXT, allowNull: true },
      Sep_2021: { type: DataTypes.TEXT, allowNull: true },
      Jun_2021: { type: DataTypes.TEXT, allowNull: true },
      Dec_2024: { type: DataTypes.TEXT, allowNull: true },
      Sep_2023: { type: DataTypes.TEXT, allowNull: true },
    },
    {
      tableName: 'shareholding_pattern_shareholding_pattern',
      timestamps: false,
      freezeTableName: true,
    }
  );
}
